
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/absence?serverTimezone=GMT%2B8
    username: Nameless
    password: 123456
#  web:
#    resources:
#      static-locations:
#        classpath: src//main//files//




mybatis:
  mapper-locations: classpath:mapper/*.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






#files:
#  upload:
#    path: E:\Learning\手机应用开发\springBoot\files
